services:
  bambu-timelapse-downloader:
    image: ghcr.io/gclenaghan/bambu-timelapse-downloader:latest
    container_name: bambu-timelapse-downloader
    restart: unless-stopped
    environment:
      - PRINTER_IP
      - ACCESS_CODE
      - SERIAL_NUMBER
      - DELETE_AFTER_DOWNLOAD=${DELETE_AFTER_DOWNLOAD:-false}
    volumes:
      - ${DOWNLOADS_HOST_PATH}:/downloads
